name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13']

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: pip install uv

    - name: Install Dependencies
      run: uv sync

    - name: Linting
      run: uv run ruff check .

    - name: Formatting Check
      run: uv run ruff format --check .

    - name: Install Headless Dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Run Tests
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          uv run xvfb-run pytest
        else
          uv run pytest
        fi
      shell: bash
